site_name: "Bits 'n Bots"
site_description: 'What is happening in the lab!'
site_author: 'Alan Yorinks'
site_url: 'https://mryslab.github.io/bits-n-bots'

copyright: >
  Copyright &copy; 2023 Alan Yorinks

theme:
  name: 'material'
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:


    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7


        name: Switch to dark mode



plugins:
  - blog:
      blog_dir: .
  - social
  - search


extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:MisterYsLab@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/MrYsLab
