site_name: "Bits 'n Bots"
site_description: "Mr. Y's Lab blog."
site_author: 'Alan Yorinks'
site_url: 'https://mryslab.github.io/bits-n-bots'

copyright: >
  Copyright &copy; 2023-2025 Alan Yorinks

theme:
  name: 'material'
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:


    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
  features:
    - navigation.footer



    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      post_excerpt_separator: <!-- more -->
      post_excerpt: required
      post_readtime: true

  - social
  - search
  - open-in-new-tab


extra:
  analytics:
    provider: google
    property: G-72FWR7622V
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:MisterYsLab@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/MrYsLab
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/mryslab.bsky.social

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
